export const LABOUR_TYPE_OPTIONS = [
    'Cut & Edge',
    'Assemble',
    'Assemble Kick',
    'Delivery Drive',
    'Delivery Unload',
    'Installer Travel',
    'Install',
    'Install Splashback',
    'Removal',
    'Sand & Spray',
    'Re Assemble 2pac',
    'Site Measure',
    'Dress Timber',
    'Quote & Draw',
    'Project management',
    'Load Truck',
    'Make & Install LED Strip',
    'CNC Machine Time',
    'Pack Hardware',
    'Laminate and file Edges',
    'Living Away Allowance',
    'Template Allowance',
    'Travel Time',
    'Laminate Kicks',
    'Stain',
    'Sanding',
  ]
  